CREATE OR REPLACE
TRIGGER TG_SUFIXO BEFORE
INSERT
	ON
	Depto FOR EACH ROW
BEGIN
	:NEW.NOMEDEPTO := :NEW.NOMEDEPTO || 'sons';
END;


CREATE OR REPLACE
TRIGGER TG_DOUTOR BEFORE
INSERT
	OR
UPDATE
	OF codtit ON
	professor FOR EACH ROW
BEGIN
	IF :NEW.codtit = 1 THEN RAISE_APPLICATION_ERROR(-20000,
	'Titulação Inválida');
END IF;
END;